export enum OrderTypeEnum {
  AGENT_FULLY_PAID = "AGENT_FULLY_PAID",
  AGENT_PAY_ON_DELIVERY = "AGENT_PAY_ON_DELIVERY",
  DOORSTEP_FULLY_PAID = "DOORSTEP_FULLY_PAID",
  DOORSTEP_PAY_ON_DELIVERY = "DOORSTEP_PAY_ON_DELIVERY",
  ERRAND = "ERRAND",
}
